version: '3.8'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ava-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - ava-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: ava-nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - ava-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: ava-db
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - ava-network

networks:
  ava-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
