version: '3.8'

services:
  # PHP-FPM Service (Laravel backend)
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: iewa-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - iewa-network

  # Nginx Service (web server)
  nginx:
    image: nginx:alpine
    container_name: iewa-nginx
    restart: unless-stopped
    ports:
      - '8080:80'  # Laravel app at http://localhost:8080
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - iewa-network

  # MySQL Service (database)
  db:
    image: mysql:8.0
    container_name: iewa-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - iewa-network

  # phpMyAdmin (database UI)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: iewa-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ARBITRARY: 1
    ports:
      - '8088:80' # phpMyAdmin at http://localhost:8088
    depends_on:
      - db
    networks:
      - iewa-network

networks:
  iewa-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
